package jieqi.ai;

import jieqi.common.Move;

import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.Random;

/**
 * L0 baseline agent: uniformly picks one legal move generated by the shared rule engine.
 */
public final class RandomAgent implements Agent {

    private final Random random;

    public RandomAgent() {
        this(new Random());
    }

    public RandomAgent(long seed) {
        this(new Random(seed));
    }

    public RandomAgent(Random random) {
        this.random = Objects.requireNonNull(random, "random");
    }

    @Override
    public Optional<Move> selectMove(PlayerView view, TimeBudget budget) {
        Objects.requireNonNull(view, "view");
        Objects.requireNonNull(budget, "budget");

        List<Move> legalMoves = view.legalMoves();
        if (legalMoves.isEmpty()) {
            return Optional.empty();
        }
        return Optional.of(legalMoves.get(random.nextInt(legalMoves.size())));
    }
}
